  name: Deploy
  uses: peaceiris/actions-gh-pages@v4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./eliza
    publish_branch: main/eliza
    cname: eliza.adam.dev
    user_name: 'Adam'





               