  name: Deploy
  uses: peaceiris/actions-gh-pages@v4
  on: [push]
  jobs:
    deploy:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.74.3'
        - name: Build
          run: hugo --minify
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./eliza
    publish_branch: main/eliza
    cname: eliza.adam.dev
    user_name: 'Adam'





               